language: node_js
node_js:
  - '0.10'
before_script:
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
notifications:
     email:
         recipients:
             - agustin@arancione.io
         on_success: always
         on_failure: always

